### ISSUE TITLE
Determine which parts of ReWire.Core.Transformations need to stay and need to go.

### ISSUE THREAD

**Issue by igraves** [mu-chaco/ReWire#11]
ReWire.Core.Transformations contains a number of files that are currently in use, not in use and/or are broken.  Some of the broken ones may still be useful if they're fixed, but I'm not sure, or perhaps a future refactoring of the compiler will see all of these transformations eliminated and replaced.  Might be worth figuring out in the short term if there's stuff in here worth salvaging.

**Comment by aprocter** [comment]
This has been taken care of in master.
